[package]
name = "raytracing-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tobj = { version = "4.0.2", features = ["log"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
winit = "0.28.7"
