[package]
name = "raytracing"
version = "0.2.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
rt-engine = { path = "rt-engine" }

[workspace]
members = ["rt-engine"]
