[package]
name = "rt-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
png = { version = "0.17.14", optional = true }
tobj = { version = "4.0.2" }
tracing = "0.1.40"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
winit = "0.28.7"

[features]
default = []
image = ["dep:png"]
